apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber
spec:
  selector:
    matchLabels:
      app: kuber
  replicas: 3
  template:
    metadata:
      labels:
        app: kuber
    spec:
      containers:
      - name: mykuberapp
        image: docker.io/praveeenj/kuber:tagname
        resources:
        ports:
        - containerPort: 7000
