# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: kuber
  namespace: default
spec:
  selector:
    app: kuber
  ports:
  - name: kuber
    port: 5000
    targetPort: 7000
   
---
